apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: madara
spec:
  serviceName: madara-service
  replicas: 2
  selector:
    matchLabels:
      app: madara
  template:
    metadata:
      labels:
        app: madara
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: madara
          image: docker.io/uacias/madara:latest
          args:
            - "--name"
            - "madara"
            - "--base-path"
            - "/madara/data"
            - "--network"
            - "test"
            - "--l1-endpoint"
            - "http://anvil-service:8545"
            - "--full"
            - "--gateway-key"
            - "$(GATEWAY_KEY)"
          envFrom:
            - secretRef:
                name: secret
          ports:
            - containerPort: 9944
          volumeMounts:
            - name: madara-data
              mountPath: /madara/data
  volumeClaimTemplates:
    - metadata:
        name: madara-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: madara-service
spec:
  clusterIP: None
  selector:
    app: madara
  ports:
    - name: http
      protocol: TCP
      port: 9944
      targetPort: 9944
