apiVersion: batch/v1
kind: Job
metadata:
  name: setup-data-pathfinder
spec:
  template:
    spec:
      containers:
        - name: setup-data-pathfinder
          image: docker.io/uacias/patfinder-dbs:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Copying data for pathfinder instances..." && \
              cp /mnt/data/original/testnet-sepolia.sqlite /mnt/shared-data/testnet-sepolia.sqlite
          volumeMounts:
            - name: shared-data
              mountPath: /mnt/shared-data
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/shared-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
