apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - job-pathfinder.yaml

secretGenerator:
  - name: secret
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
